### ISSUE TITLE
doesnt work after update

### ISSUE THREAD

**Issue by mpralle** [alextud/ha-switchbot-curtain#23]
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 249, in _async_setup_platform
    await asyncio.shield(task)
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 52, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/switchbot-curtain/cover.py", line 41, in setup_platform
    add_entities([SwitchBotCurtain(mac_addr, name, password)])
  File "/config/custom_components/switchbot-curtain/cover.py", line 56, in __init__
    self._device = switchbot.SwitchbotCurtain(mac=mac, password=password)
AttributeError: module 'switchbot' has no attribute 'SwitchbotCurtain'

config:
cover:
  - platform: switchbot-curtain
    mac: C8:21:BE:8C:9E:xx

installed the integration via hacs

**Comment by mpralle** [comment]
after deleting a switchbot switch everything works fine again
