### ISSUE TITLE
Im new to HA please be gentle lol but i have a problem

### ISSUE THREAD

**Issue by pprobbins** [alextud/ha-switchbot-curtain#24]
I downloaded the files and copied them to the config directory but when i try and restart the server i get the error 'Integration 'switchbot-curtain' not found'
 can anyone help please?

this is the ha log

Logger: homeassistant.components.websocket_api.http.connection
Source: components/hassio/__init__.py:562
Integration: Home Assistant WebSocket API (documentation, issues)
First occurred: 19:24:18 (1 occurrences)
Last logged: 19:24:18

[139692267184864] The system cannot restart because the configuration is not valid: Platform error cover.switchbot-curtain - Integration 'switchbot-curtain' not found.
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 185, in handle_call_service
    await hass.services.async_call(
  File "/usr/src/homeassistant/homeassistant/core.py", line 1492, in async_call
    task.result()
  File "/usr/src/homeassistant/homeassistant/core.py", line 1527, in _execute_service
    await handler.job.target(service_call)
  File "/usr/src/homeassistant/homeassistant/components/hassio/__init__.py", line 562, in async_handle_core_service
    raise HomeAssistantError(
homeassistant.exceptions.HomeAssistantError: The system cannot restart because the configuration is not valid: Platform error cover.switchbot-curtain - Integration 'switchbot-curtain' not found.

**Comment by Excentyl** [comment]
Where exactly did you save the files? They should be in:
config\custom_components\switchbot-curtain

If you saved them directly in config (so not in the file path above), I believe you'll get errors.

Since you are new, have you heard of HACS? It is a really useful integration which allows you to install custom components such as this one from within Home Assistant. I would recommend that you look into it if you haven't already.
