### ISSUE TITLE
Fails to initialize

### ISSUE THREAD

**Issue by apollo1220** [alextud/ha-switchbot-curtain#28]
The cover fails to add to HA due to line 110. I changed locally to below to get it working
```
return True ##self.current_cover_position <= 0
```

**Comment by isewise** [comment]
> The cover fails to add to HA due to line 110. I changed locally to below to get it working
> 
> ```
> return True ##self.current_cover_position <= 0
> ```

This worked for me. 

Thanks!

**Comment by mcfarlde** [comment]
Does this fix my situation where I cannot update?



Regards

**Comment by apollo1220** [comment]
Actually I started using this because the switchbot integration provided in HA wasn't working for my setup, but I decided to try that integration again and it is now working for me (and better then this integration ever did). If you want to give that a try, make sure you completely remove this integration and restart HA before adding with the default integration (otherwise they collide and neither works).

**Comment by mcfarlde** [comment]
I just tried removing the old HACs version that works, installing the Integration (didn’t work) removed the integration, installed latest HACS version (didn’t work) and went back to the old HACs version.  Curtain works, but battery is wrong.

**Comment by niemyjski** [comment]
I'm also seeing this:

```
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 614, in _async_add_entity
    await entity.add_to_platform_finish()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 801, in add_to_platform_finish
    self.async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 553, in async_write_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 590, in _async_write_ha_state
    state = self._stringify_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 559, in _stringify_state
    if (state := self.state) is None:
  File "/usr/src/homeassistant/homeassistant/components/cover/__init__.py", line 240, in state
    if (closed := self.is_closed) is None:
  File "/config/custom_components/switchbot-curtain/cover.py", line 110, in is_closed
    return self.current_cover_position <= 0
TypeError: '<=' not supported between instances of 'NoneType' and 'int'
```

cc @alextud 

I tried changing it to 

```python
    @property
    def is_closed(self):
        """Return if the cover is closed."""
        return self.current_cover_position is not None and self.current_cover_position <= 0
```
hopefully this works.
